FROM nginx:alpine

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

COPY index.html app.js style.css /usr/share/nginx/html/
COPY images /usr/share/nginx/html/images
COPY icons /usr/share/nginx/html/icons
